"""Model re-exports for the interim SDK mirror.

For now we import directly from the backend models module so existing code
continues to operate. As we extract the SDK into its own repository, these
imports will be replaced with the local canonical definitions.
"""

from backend.models.strand import (  # type: ignore[attr-defined]
    Strand,
    StrandType,
    Difficulty,
    RelationshipType,
    VisualizationKind,
    RepresentationMode,
    PrerequisiteLevel,
    ScaffoldLevel,
    Relationship,
    LearningObjective,
    ScaffoldVariant,
    RepresentationalVariant,
    VisualizationConfig,
    MediaContent,
    StrandContent,
    StrandMetadata,
    SpiralMetadata,
    AssessmentData,
    Thread,
    Pattern,
    Weave,
    WeaveEdge,
    WeaveNode,
    AccessRole,
    PrincipalType,
    StrandPermission,
    QualityMatrix,
    AnalysisStatus,
    DocumentPageSummary,
    DocumentAnalysis,
    MediaKeyframe,
    MediaScene,
    MediaAnalysis,
)

__all__ = [
    "Strand",
    "StrandType",
    "Difficulty",
    "RelationshipType",
    "VisualizationKind",
    "RepresentationMode",
    "PrerequisiteLevel",
    "ScaffoldLevel",
    "Relationship",
    "LearningObjective",
    "ScaffoldVariant",
    "RepresentationalVariant",
    "VisualizationConfig",
    "MediaContent",
    "StrandContent",
    "StrandMetadata",
    "SpiralMetadata",
    "AssessmentData",
    "Thread",
    "Pattern",
    "Weave",
    "WeaveEdge",
    "WeaveNode",
    "AccessRole",
    "PrincipalType",
    "StrandPermission",
    "QualityMatrix",
    "AnalysisStatus",
    "DocumentPageSummary",
    "DocumentAnalysis",
    "MediaKeyframe",
    "MediaScene",
    "MediaAnalysis",
]
