"""Local mirror proxy for the OpenStrand SDK.

This package temporarily re-exports schema objects from the existing backend
modules so the client code can import from `openstrand_sdk` immediately. Once
the dedicated SDK repository is published, this module will be replaced by the
real implementation.
"""

from .models import (
    Strand,
    StrandType,
    Difficulty,
    RelationshipType,
    VisualizationKind,
    RepresentationMode,
    PrerequisiteLevel,
    ScaffoldLevel,
    Relationship,
    LearningObjective,
    ScaffoldVariant,
    RepresentationalVariant,
    VisualizationConfig,
    MediaContent,
    StrandContent,
    StrandMetadata,
    SpiralMetadata,
    AssessmentData,
    Thread,
    Pattern,
    Weave,
    WeaveEdge,
    WeaveNode,
    AccessRole,
    PrincipalType,
    StrandPermission,
    QualityMatrix,
    AnalysisStatus,
    DocumentPageSummary,
    DocumentAnalysis,
    MediaKeyframe,
    MediaScene,
    MediaAnalysis,
)

__all__ = [
    "Strand",
    "StrandType",
    "Difficulty",
    "RelationshipType",
    "VisualizationKind",
    "RepresentationMode",
    "PrerequisiteLevel",
    "ScaffoldLevel",
    "Relationship",
    "LearningObjective",
    "ScaffoldVariant",
    "RepresentationalVariant",
    "VisualizationConfig",
    "MediaContent",
    "StrandContent",
    "StrandMetadata",
    "SpiralMetadata",
    "AssessmentData",
    "Thread",
    "Pattern",
    "Weave",
    "WeaveEdge",
    "WeaveNode",
    "AccessRole",
    "PrincipalType",
    "StrandPermission",
    "QualityMatrix",
    "AnalysisStatus",
    "DocumentPageSummary",
    "DocumentAnalysis",
    "MediaKeyframe",
    "MediaScene",
    "MediaAnalysis",
]
